from pathlib import Path

path = Path('src/App.js')
source = path.read_text()

if 'function AdditionalServices(){' not in source:
    page = r'''function AdditionalServices(){const items=[
{title:"Mechanical & Electrical Supplies and Services",icon:Wrench,image:"https://images.unsplash.com/photo-1473341304170-971dccb5ac1e",text:"Industrial motors, gearboxes, pumps, blowers, compressors, belt conveyors, bearings, gaskets, valves, pneumatic fittings, SS/MS pipes, flanges and related accessories. Electrical panels, breakers, contactors, relays, cables, lighting and wiring accessories. Repair, maintenance, replacement, on-site troubleshooting and technical support, plus hand pallet lifter parts, hand trolleys, platform trolleys, pallet jacks, ropes, chains and cargo straps."},
{title:"Utilities & Facility Maintenance Supplies and Services",icon:Wrench,image:"https://images.unsplash.com/photo-1581092921461-eab62e97a780",text:"Maintenance and repair support for water, compressed air, steam and other utility systems, plus maintenance consumables, preventive and corrective maintenance, AMC support, air compressor parts and boiler parts."},
{title:"Boiler Chemicals – Supply and Services",icon:FlaskConical,image:"https://haoshpumps.com/wp-content/uploads/2024/01/Boiler-Chemical-for-Dosing-Pump.jpg",text:"Boiler water-treatment chemicals including scale inhibitors, oxygen scavengers and pH adjusters, dosing systems, monitoring, on-site testing, analysis and recommendations to improve efficiency and protect equipment from corrosion and scaling."},
{title:"Seamless MS & SS Pipes and Fittings",icon:Wrench,image:"https://www.maxim-tube.com/wp-content/uploads/2023/05/stainless-steel-pipe-fittings.jpg",text:"Seamless Mild Steel and Stainless Steel pipes and fittings in different schedules, grades and sizes, including flanges, elbows, reducers, tees and related accessories according to project requirements."},
{title:"Wastewater Treatment Plant (WWTP) Supplies and Services",icon:Factory,image:"https://static.wixstatic.com/media/b9b6ed_22bbec6674af4fb0b309bcc93509af32~mv2.jpg/v1/fill/w_980%2Ch_735%2Cal_c%2Cq_85%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/b9b6ed_22bbec6674af4fb0b309bcc93509af32~mv2.jpg",text:"WWTP pumps, blowers, diffusers and dosing systems; coagulants, flocculants and disinfectants; operation and maintenance support; and technical guidance for performance improvement and compliance."},
{title:"HVAC Systems – Supplies and Services",icon:Snowflake,image:"https://mojoair.com.au/assets/images/web-image-industrial.jpg",text:"Supply and installation of chillers, AHUs, FCUs, exhaust and fresh-air systems and ducting, HVAC parts, preventive and corrective maintenance, filter replacement, duct cleaning and performance optimization."},
{title:"Waterproofing Solutions – Supplies and Services",icon:Building2,image:"https://www.constructionlondon.co.uk/gallery/6695/8f21032a-3505-476c-9dee-f9ffa11326ff.jpg",text:"Supply and application of waterproof chemicals and membranes for roofs, basements, water tanks and wet areas, including leakage rectification and long-term protective solutions."},
{title:"Pumps, Valves, and Pneumatic Fittings",icon:Wrench,image:"https://www.rivistacmi.it/uploads/tx_etim/RS_COMPONENTS-pneumatics-image.jpg",text:"Industrial centrifugal, submersible and dosing pumps; gate, globe, butterfly, check and ball valves; pneumatic fittings, hoses, regulators and accessories; and selection support based on process and application requirements."}
];return <section className="section section-light"><div className="container"><SectionLabel>ADDITIONAL ENGINEERING / SUPPLY SERVICES</SectionLabel><div className="section-heading"><h2>Industrial supplies and specialist services for complete project support.</h2><p>We source, supply, install and support equipment and materials according to your technical specifications, project requirements and maintenance needs.</p></div><div className="cap-grid">{items.map((s,i)=><article className="service-card" key={s.title}><div className="service-card-image"><img loading="lazy" decoding="async" src={img(s.image)} alt={s.title}/><span>{String(i+1).padStart(2,'0')}</span></div><div className="service-card-body"><s.icon size={22}/><h3>{s.title}</h3><p>{s.text}</p><div className="service-features"><span><CheckCircle2 size={15}/> Supply & sourcing</span><span><CheckCircle2 size={15}/> Technical support</span></div></div></article>)}</div></div></section>}
'''
    marker = 'function Services(){'
    if marker not in source:
        raise SystemExit('Services component marker not found')
    source = source.replace(marker, page + '\nfunction ServicesOriginal(){', 1)
    wrapper = 'function Services(){return <><ServicesOriginal/><AdditionalServices/></>}\n'
    source = source.replace('function ServicesOriginal(){', wrapper + 'function ServicesOriginal(){', 1)
    path.write_text(source)
