import React from "react";
import { ArrowUpRight, Instagram, Mail, MapPin, MessageCircle, Phone, Menu, X } from "lucide-react";
import "./ContactPage.css";
import "./ContactFooter.css";

const navItems = [["Home","/"],["Services","/services"],["General Order Supplies","/supplies"],["IT Services","/it-services"],["Industries","/industries"],["Our Clients","/clients"],["Contact Us","/contact"]];
const officeAddress="593 Block-A LDA Avenue, 1 Raiwind Rd, Lahore, 54000";
const mapsUrl="https://www.google.com/maps/dir/?api=1&destination=593+Block-A+LDA+Avenue,+1+Raiwind+Rd,+Lahore,+54000";
const emailAddress="na.engineeringsolutions2023@gmail.com";
const emailUrl=`https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(emailAddress)}`;

export default function ContactPage(){
  const [open,setOpen]=React.useState(false);
  const cards=[
    {icon:MapPin,title:"Lahore Office",text:officeAddress,href:mapsUrl,label:"Get directions in Google Maps"},
    {icon:Phone,title:"Primary Phone",text:"+92 300 8596393",href:"tel:+923008596393",label:"Call us"},
    {icon:Phone,title:"Alternate Phone",text:"+92 302 6880398",href:"tel:+923026880398",label:"Call us"},
    {icon:Mail,title:"Email",text:emailAddress,href:emailUrl,label:"Send an email"},
  ];
  return <div className="contact-site">
    <header className="contact-header"><div className="contact-container contact-nav-wrap"><a href="/" className="contact-logo"><img src="/logo.png" alt="NA Engineering Solutions"/><span><b>NA ENGINEERING</b><small>SOLUTIONS</small></span></a><button className="contact-menu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button><nav className={open?"contact-nav open":"contact-nav"}>{navItems.map(([label,to])=><a key={to} href={to} onClick={()=>setOpen(false)} className={to==="/contact"?"active":""}>{label}</a>)}</nav></div></header>
    <section className="contact-intro"><div className="contact-container"><span className="contact-eyebrow"><i/> CONTACT US / NA ENGINEERING SOLUTIONS</span><h1>Let's work together.</h1><p>Have an engineering, supply, maintenance or project requirement? Contact NA Engineering Solutions directly — <strong>no form required.</strong></p></div></section>
    <main>
      <section className="contact-section contact-light"><div className="contact-container contact-main-grid"><div className="contact-main-copy"><span className="contact-eyebrow dark"><i/> GET IN TOUCH</span><h2>Speak directly with our team.</h2><p>Whether you need engineering services, industrial supplies, facility maintenance, project support or General Order Supplies &amp; Services, our team is ready to discuss your requirement.</p><p>Call us, email us, message us on WhatsApp, visit our Lahore office or open our website — choose the contact method that works best for you.</p><div className="contact-buttons"><a className="contact-btn primary" href="https://wa.me/923008596393?text=Hello%20NA%20Engineering%20Solutions%2C%20I%20would%20like%20to%20discuss%20a%20requirement." target="_blank" rel="noreferrer"><MessageCircle size={18}/> WhatsApp Us <ArrowUpRight size={16}/></a><a className="contact-btn secondary" href={emailUrl} target="_blank" rel="noreferrer"><Mail size={18}/> Email Us <ArrowUpRight size={16}/></a></div></div><div className="contact-card-grid">{cards.map(({icon:Icon,title,text,href,label})=><a className="contact-card" href={href} target={href.startsWith("http")?"_blank":undefined} rel={href.startsWith("http")?"noreferrer":undefined} key={title}><span className="contact-card-icon"><Icon size={21}/></span><span><b>{title}</b><strong>{text}</strong><small>{label} <ArrowUpRight size={13}/></small></span></a>)}</div></div></section>
      <section className="contact-section contact-dark"><div className="contact-container contact-details-grid"><div><span className="contact-eyebrow"><i/> COMPANY CONTACT DETAILS</span><h2>NA Engineering Solutions</h2><p>General Order Supplier | Engineering | Maintenance Services</p></div><div className="contact-detail-list"><div><span>Office</span><b>{officeAddress}</b></div><div><span>Phone</span><b>+92 300 8596393 &nbsp; | &nbsp; +92 302 6880398</b></div><div><span>Email</span><a href={emailUrl} target="_blank" rel="noreferrer">{emailAddress}</a></div><div><span>Website</span><a href="https://www.naengineeringsolutions.com" target="_blank" rel="noreferrer">www.naengineeringsolutions.com <ArrowUpRight size={14}/></a></div></div></div></section>
      <section className="contact-section contact-light"><div className="contact-container"><span className="contact-eyebrow dark"><i/> WHAT YOU CAN CONTACT US ABOUT</span><div className="contact-heading"><h2>One team for engineering, supplies and support.</h2><p>Contact us for complete or individual requirements across our service and supply capabilities.</p></div><div className="contact-service-grid">{["Civil Engineering","HVAC Systems","Mechanical Engineering","PEB Works","Electrical Works","Fire Fighting","Safety & Security Systems","Industrial Maintenance","Mechanical & Electrical Supplies","Utilities & Facility Maintenance","General Order Supplies & Services","IT Services"].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><b>{x}</b><ArrowUpRight size={15}/></div>)}</div></div></section>
      <section className="contact-map"><div className="contact-container contact-map-inner"><div><span className="contact-eyebrow"><i/> VISIT OUR LAHORE OFFICE</span><h2>{officeAddress}</h2><p>Get turn-by-turn directions directly to our Lahore office.</p></div><a href={mapsUrl} target="_blank" rel="noreferrer">Get Directions <ArrowUpRight size={17}/></a></div></section>
    </main>
    <footer className="contact-footer"><div className="contact-container contact-footer-grid"><div className="contact-footer-brand"><a href="/" className="contact-logo"><img src="/logo.png" alt="NA Engineering Solutions"/><span><b>NA ENGINEERING</b><small>SOLUTIONS</small></span></a><p>Engineering • Construction • Industrial<br/>Solutions • General Order Supplies &amp;<br/>Services</p><div className="contact-socials"><a href="https://www.tiktok.com/" target="_blank" rel="noreferrer" aria-label="TikTok">♪</a><a href="https://www.instagram.com/" target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={17}/></a><a href="https://x.com/" target="_blank" rel="noreferrer" aria-label="X">𝕏</a></div></div><div className="contact-footer-col"><h4>COMPANY</h4><a href="/">Home</a><a href="/services">Services</a><a href="/supplies">General Order Supplies</a><a href="/it-services">IT Services</a><a href="/industries">Industries</a><a href="/clients">Our Clients</a><a href="/contact">Contact Us</a></div><div className="contact-footer-col"><h4>SERVICES</h4><a href="/services/civil-engineering">Civil Engineering</a><a href="/services/mechanical-engineering">Mechanical Engineering</a><a href="/services/peb-works">PEB Works</a><a href="/services/electrical-works">Electrical Works</a><a href="/services/mechanical-electrical-supplies">Mechanical &amp; Electrical Supplies and Services</a></div><div className="contact-footer-col contact-footer-contact"><h4>CONTACT</h4><a className="footer-email" href={emailUrl} target="_blank" rel="noreferrer"><Mail size={18}/> <strong>{emailAddress}</strong></a><a href="tel:+923008596393"><Phone size={17}/> +92 300 8596393</a><a href="tel:+923026880398"><Phone size={17}/> +92 302 6880398</a><a href={mapsUrl} target="_blank" rel="noreferrer"><MapPin size={17}/> {officeAddress}</a><div className="contact-footer-ceo"><small>CEO</small><strong>Muhammad<br/>Boota</strong></div></div></div><div className="contact-footer-bottom"><div className="contact-container"><span>© 2026 NA Engineering Solutions</span><span>Built for dependable project delivery.</span></div></div></footer>
  </div>;
}
